# Generated by Django 5.0.3 on 2026-04-22 18:25

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_type', models.CharField(choices=[('HEAD_OF_STATE', 'Head of State / Former Head of State'), ('MINISTER', 'Minister / Deputy Minister'), ('DIPLOMATIC_MISSION', 'Diplomatic Mission'), ('MULTILATERAL_ORG', 'Multilateral Organisation'), ('DIASPORA_ORGANISATION', 'Diaspora Organisation'), ('ACADEMIC', 'Academic / Researcher'), ('MEDIA', 'Media'), ('OBSERVER', 'Observer / General Participant')], max_length=40)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('country_residence', models.CharField(max_length=150)),
                ('nationality', models.CharField(blank=True, max_length=150, null=True)),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation_country', models.CharField(blank=True, max_length=150, null=True)),
                ('diaspora_affiliation', models.BooleanField(default=False)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('consent_given', models.BooleanField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRegistration',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('registration_type', models.CharField(choices=[('HEAD_OF_STATE', 'Head of State / Former Head of State'), ('MINISTER', 'Minister / Deputy Minister'), ('DIPLOMATIC_MISSION', 'Diplomatic Mission'), ('MULTILATERAL_ORG', 'Multilateral Organisation'), ('DIASPORA_ORGANISATION', 'Diaspora Organisation'), ('ACADEMIC', 'Academic / Researcher'), ('MEDIA', 'Media'), ('OBSERVER', 'Observer / General Participant')], max_length=40)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('country_residence', models.CharField(max_length=150)),
                ('nationality', models.CharField(blank=True, max_length=150, null=True)),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation_country', models.CharField(blank=True, max_length=150, null=True)),
                ('diaspora_affiliation', models.BooleanField(default=False)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('consent_given', models.BooleanField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical registration',
                'verbose_name_plural': 'historical registrations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
